return {
  colorscheme_1 = 'default',
  colorscheme_2 = 'rose-pine',
  colorscheme_3 = 'gruvbox',
  colorscheme_4 = 'github_dark_high_contrast',

  colors = {
    black = '#0B0C11',
    white = '#d7dae1',
    red = '#ffbcb5',
    green = '#7FAD8A',
    blue = '#7FAAC9',
    yellow = '#f4d88c',
    gray = '#d7dae1',
    darkgray = '#0B0C11',
    lightgray = '#303340',
    inactivegray = '#303340',
  },

  icons = {
    diagnostics = {
      Error = ' ',
      Warn = ' ',
      Hint = ' ',
      Info = ' ',
    },
    git = {
      added = ' ',
      modified = ' ',
      removed = ' ',
    },
    kinds = {
      Array = ' ',
      Boolean = '󰨙 ',
      Class = ' ',
      Codeium = '󰘦 ',
      Color = ' ',
      Control = ' ',
      Collapsed = ' ',
      Constant = '󰏿 ',
      Constructor = ' ',
      Copilot = ' ',
      Enum = ' ',
      EnumMember = ' ',
      Event = ' ',
      Field = ' ',
      File = ' ',
      Folder = ' ',
      Function = '󰊕 ',
      Interface = ' ',
      Key = ' ',
      Keyword = ' ',
      Method = '󰊕 ',
      Module = ' ',
      Namespace = '󰦮 ',
      Null = ' ',
      Number = '󰎠 ',
      Object = ' ',
      Operator = ' ',
      Package = ' ',
      Property = ' ',
      Reference = ' ',
      Snippet = '  ',
      String = ' ',
      Struct = '󰆼 ',
      Supermaven = ' ',
      TabNine = '󰏚 ',
      Text = ' ',
      TypeParameter = ' ',
      Unit = ' ',
      Value = ' ',
      Variable = '󰀫 ',
    },
    chars = {
      ellipsis = '…',
    },
  },

  lazy = {
    icons = {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },

  position = {
    center = {
      row = '50%',
      col = '50%',
    },
  },

  set_colorscheme = require('lib.utils.set_colorscheme').run,
}
