
return {}

-- return {
--   {
--     'neovim/nvim-lspconfig',
--     opts = function(_, opts)
--       if vim.g.performance then
--         opts.inlay_hints = { enabled = false }
--       end
--
--       opts.diagnostics.virtual_text = false
--       opts.diagnostics.float = { border = 'rounded', source = true }
--
--       opts.servers.ols = {}
--       require 'config.lsp.eslint'
--
--       opts.servers['*'] = opts.servers['*'] or {}
--       opts.servers['*'].keys = {
--         { 'gr', false },
--         { 'gI', vim.lsp.buf.implementation, desc = 'Goto Implementation' },
--       }
--
--       opts.servers.gopls = {
--         settings = {
--           gopls = {
--             gofumpt = true,
--             codelenses = {
--               gc_details = false,
--               generate = true,
--               regenerate_cgo = true,
--               run_govulncheck = true,
--               test = true,
--               tidy = true,
--               upgrade_dependency = true,
--               vendor = true,
--             },
--             hints = {
--               assignVariableTypes = true,
--               compositeLiteralFields = true,
--               compositeLiteralTypes = true,
--               constantValues = true,
--               functionTypeParameters = true,
--               parameterNames = true,
--               rangeVariableTypes = true,
--             },
--             analyses = {
--               nilness = true,
--               unusedparams = true,
--               unusedwrite = true,
--               useany = true,
--               ST1003 = false, -- annoying CamelCase warning BS
--             },
--             usePlaceholders = true,
--             completeUnimported = true,
--             staticcheck = true,
--             directoryFilters = { '-.git', '-.vscode', '-.idea', '-.vscode-test', '-node_modules' },
--             semanticTokens = true,
--           },
--         },
--       }
--
--       opts.servers.vtsls.settings.typescript.tsserver =
--         vim.tbl_deep_extend('force', opts.servers.vtsls.settings.typescript.tsserver or {}, {
--           maxTsServerMemory = 8192,
--         })
--       opts.servers.vtsls.capabilities = vim.tbl_deep_extend('force', opts.servers.vtsls.capabilities or {}, {
--         documentFormattingProvider = false,
--         documentRangeFormattingProvider = false,
--       })
--       opts.servers.vtsls.keys = {
--         {
--           'gD',
--           function()
--             local params = vim.lsp.util.make_position_params()
--             LazyVim.lsp.execute {
--               command = 'typescript.goToSourceDefinition',
--               arguments = { params.textDocument.uri, params.position },
--               open = true,
--             }
--           end,
--           desc = 'Goto Source Definition',
--         },
--         {
--           'gR',
--           function()
--             LazyVim.lsp.execute {
--               command = 'typescript.findAllFileReferences',
--               arguments = { vim.uri_from_bufnr(0) },
--               open = true,
--             }
--           end,
--           desc = 'File References',
--         },
--         {
--           '<leader>oi',
--           LazyVim.lsp.action['source.organizeImports'],
--           desc = 'Organize Imports',
--         },
--         {
--           '<leader>ami',
--           LazyVim.lsp.action['source.addMissingImports.ts'],
--           desc = 'Add missing imports',
--         },
--         {
--           '<leader>ru',
--           LazyVim.lsp.action['source.removeUnused.ts'],
--           desc = 'Remove unused imports',
--         },
--         {
--           '<leader>fA',
--           LazyVim.lsp.action['source.fixAll.ts'],
--           desc = 'Fix all diagnostics',
--         },
--         {
--           '<leader>cV',
--           function()
--             LazyVim.lsp.execute { command = 'typescript.selectTypeScriptVersion' }
--           end,
--           desc = 'Select TS workspace version',
--         },
--       }
--     end,
--   },
-- }
